### ISSUE TITLE
'bold' option is not working

### ISSUE THREAD

**Issue by niguiecandy** [borntyping/python-colorlog#103]
Hi,
first of all I'd like to thank you for a great tool.
I tried to use the formatter and encountered an issue that seems to be a bug.
In your [documentation](https://pypi.org/project/colorlog/) the bold/bright font can be set using following format :

> `bold`, `bold_{color}`, `fg_bold_{color}`, `bg_bold_{color}`: Bold/bright colors.

When set, the output log turns gray.
Since `thin` option works as expected, there seems to be a bug on `bold` style.

**Comment by borntyping** [comment]
These codes can be extremely dependent on the terminal you're using and it's configuration. A lot of terminals allow uses to disable bold fonts.

I've added a sample script that might help debugging issues like this: https://github.com/borntyping/python-colorlog/blob/main/doc/colors.py

This currently works as far as I can tell, but feel free to open a new issue if you can provide some steps to reproduce the problem.
