### ISSUE TITLE
Typing information is missing on import.

### ISSUE THREAD

**Issue by DriesSchaumont** [borntyping/python-colorlog#104]
Hi!

After importing colorlog and using a type checking tool like  `mypy`, I get:
`error: Skipping analyzing 'colorlog': found module but no type hints or library stubs`

Would you consider making this information available as per [https://www.python.org/dev/peps/pep-0561/#id18](PEP561)
Thanks for creating this tool!

Dries

**Comment by borntyping** [comment]
Released in [6.1.0a1](https://pypi.org/project/colorlog/6.1.0a1/), implemented in https://github.com/borntyping/python-colorlog/commit/8ca1d3615123f505ec7294a6e21f569414f9a66b. Thanks!

**Comment by DriesSchaumont** [comment]
Woa, that was fast! Thanks @borntyping
