### ISSUE TITLE
ModuleNotFoundError: No module named 'colorlog'

### ISSUE THREAD

**Issue by SAVAMforWIN** [borntyping/python-colorlog#109]
i'm trying to use colorlog but when i try to use it i get the error in description, obviously the package is installed i don't understand why it can't find it

![image](https://user-images.githubusercontent.com/34774419/126896653-8009f5c6-3780-49af-b7d0-24da405c63fb.png)

![image](https://user-images.githubusercontent.com/34774419/126896702-4533c25a-06c3-4cfc-bf63-3e4301451327.png)

**Comment by borntyping** [comment]
It looks like you're using [pipenv](https://pipenv.pypa.io/en/latest/), which manages your project's dependencies separately.

Try running `pipenv install colorlog`.

https://pipenv.pypa.io/en/latest/install/#installing-packages-for-your-project
