### ISSUE TITLE
hope add predefined level such as colorlog.ERROR colorlog.DEBUG and so on 

### ISSUE THREAD

**Issue by iamqiz** [borntyping/python-colorlog#111]
firstly,thanks you very much  to develop the nice project; 

here is  my question:

when I use logger.setLevel ,i want use colorlog.XXXXX  instead of logging.XXXX  as level
my code now is:
```python 
import colorlog
logger=colorlog.getLogger("test_colorlog")
import logging
logger.setLevel(logging.DEBUG)
```
but i hope:
```python 
import colorlog
logger=colorlog.getLogger("test_colorlog")
logger.setLevel(colorlog.DEBUG)
```
Would you consider adding this feature? thanks

**Comment by borntyping** [comment]
Released in [6.4.1](https://github.com/borntyping/python-colorlog/releases/tag/v6.4.1), thanks!
