### ISSUE TITLE
[Bug] colorlog.basicConfig() doesn't seems to work when upgrading from v5 to v6

### ISSUE THREAD

**Issue by EmrysMyrddin** [borntyping/python-colorlog#112]
Hi,
I've just updated colorlog on my project from v5 to v6, but colors stopped showing up in the console.

It seems that it comes from the merge of `TTYColoredFormatter` and `ColoredFormatter`.
The `_blank_escape_codes` function is returning true when `os.stdout` is passed as the `stream` parameter.

I suppose that this is an heuristic to avoid printing escape codes into the some non compatible strem, but the condition is too broad. For example, in most IDE, the stdout is not linked to a TTY but handles colors very well.

Perhaps the better fix, to avoid breaking change is to add an optional parameter like `force_colors` ?

**Comment by borntyping** [comment]
Implemented and released in [6.6.0](https://github.com/borntyping/python-colorlog/releases/tag/v6.6.0). :)

**Comment by EmrysMyrddin** [comment]
Wow ! Thank you a lot for your reactivity !

This package is really great, thank you for all :-)
