### ISSUE TITLE
Doesn't support defaults

### ISSUE THREAD

**Issue by d3dave** [borntyping/python-colorlog#123]
Python 3.10 added `defaults` to `logging.Formatter`, which is quite useful: https://docs.python.org/3/library/logging.html?highlight=logging#logging.Formatter

Would be handy to have it in colorlog's ColoredFormatter as well.

**Comment by borntyping** [comment]
This should be supported properly in 6.7.0, thanks :)

https://pypi.org/project/colorlog/6.7.0/
