### ISSUE TITLE
Update default_log_colors from log_colors instead of replace it

### ISSUE THREAD

**Issue by espdev** [borntyping/python-colorlog#125]
Hello,

It would be nice to update `default_log_colors` dictionary from `log_colors` argument instead of replace it. For example, I want to change only a couple of log level colors, not all:

```python
formatter = ColoredFormatter(
    ...
    log_colors={
        'DEBUG': 'light_white',
    },
)
```

In the current implementation I will lost color for other log levels because `log_colors` just replace `default_log_colors`:
```python
self.log_colors = log_colors if log_colors is not None else default_log_colors
```

I propose to make the following changes in the constructor:

```python
if log_colors is not None:
    log_colors_new = default_log_colors.copy()
    log_colors_new.update(log_colors)
    self.log_colors = log_colors_new
else:
    self.log_colors = default_log_colors
```

Thanks!

**Comment by borntyping** [comment]
You can do easily this by merging the `default_log_colors` dictionary into a new one:

```python
formatter = ColoredFormatter(
    ...
    log_colors={
        **colorlog.default_log_colors,
        'DEBUG': 'light_white',
    },
)
```

This will give you a ColoredFormatter that uses `light_white` for DEBUG records but still uses the default for other records.

---

Changing how the constructor works here would also mean it'd need a way to unset the defaults and would be a breaking change. For example, this wouldn't work the same way anymore:

```python
formatter = ColoredFormatter(log_colors={'ERROR': 'light_white'})
```

At the moment that will make ERROR the _only_ coloured records, instead of just changing the color of ERROR and using the default for other levels.

**Comment by espdev** [comment]
@borntyping thanks for the response

Suggested approach unfortunately will not work with log configs. For logging configuration I use dictConfig from yaml file:

```yaml
logging:
  formatters:
    colored:
      (): "colorlog.ColoredFormatter"
      format: "..."
      log_colors:
        INFO: "white"
        DEBUG: "light_blue"
``` 

In this case I cannot update `log_colors` from `colorlog.default_log_colors` in the config.

> Changing how the constructor works here would also mean it'd need a way to unset the defaults and would be a breaking change. For example, this wouldn't work the same way anymore:

I agree. Suggested behavior by me is breaking changes. It's not good, so best left as is.

**Comment by borntyping** [comment]
An alternative that would work in the case of dictConfig would be to add a new parameter, though the code in `Formatter.__init__` is already quite messy. It's probably easier to just copy the defaults into the dictConfig, as there aren't very many and they don't change:

```yaml
logging:
  formatters:
    colored:
      (): "colorlog.ColoredFormatter"
      format: "..."
      log_colors:
        WARNING: "yellow"
        ERROR: "red"
        CRITICAL: "bold_red"

        INFO: "white"
        DEBUG: "light_blue"
```
