### ISSUE TITLE
Time for every log

### ISSUE THREAD

**Issue by s-y** [borntyping/python-colorlog#19]
Hello. 

It will be nice have optional  time on it 
``` [D 150220 19:57:29 hitta:85] ```
https://github.com/tornadoweb/tornado/blob/master/tornado/log.py#L70

**Comment by borntyping** [comment]
You can already do this with `colorlog` - see the documentation for [`colorlog.formatter`](https://github.com/borntyping/python-colorlog#arguments) and [`logging.Formatter`](https://docs.python.org/3/library/logging.html#logging.Formatter).
