### ISSUE TITLE
Add ability to define log_colors and secondary_log_colors in INI file

### ISSUE THREAD

**Issue by chrisgeo** [borntyping/python-colorlog#20]
This might be possible and I'm missing it. It would be great if we could define these in a logging INI config file with something akin to:

```ini
[formatter_color]
class=colorlog.ColoredFormatter
format=%(log_color)s%(levelname)-8s%(reset)s [%(name)s]%(reset)s %(message)s%(reset)s
datefmt=%m-%d %H:%M:%S
log_colors=
    DEBUG='cyan'
    INFO='green',
    WARNING='yellow',
    ERROR='red',
    CRITICAL='red,bg_white'
```

**Comment by borntyping** [comment]
This should be possible using the `args` configuration option described in the Python documentation for the logging module: [15.8.3. Configuration file format](https://docs.python.org/2/library/logging.config.html#logging-config-fileformat) (if not, that's a problem with the `logging` library and out of the scope of `colorlog`).
