### ISSUE TITLE
secondary_log_color pydoc is incorrect

### ISSUE THREAD

**Issue by FranciscoBorges** [borntyping/python-colorlog#23]
in short, doc states it is `log_color_{key}` but code does `{key}_log_color`.

At colorlog.py line 76, we have
```
 The ``secondary_log_colors`` argument can be used to create additional
        ``log_color`` attributes. Each key in the dictionary will set
        ``log_color_{key}``, using the value to select from a different
        ``log_colors`` set.
```

but the code (colorlog.py line 124) is doing:
```
setattr(record, name + '_log_color', color)
```

**Comment by e4r7hbug** [comment]
I believe this has been resolved with the closing of #24. If I had done more searching, I would've noticed this and mentioned it in the commit message.
