### ISSUE TITLE
Please ship tests to pypi

### ISSUE THREAD

**Issue by jlec** [borntyping/python-colorlog#28]
Downstream devs love to test. Please ship the tests in the pypi tarball.

**Comment by borntyping** [comment]
Sure. Is there any reason you're not using the source tarballs from GitHub though?

**Comment by jlec** [comment]
> Is there any reason you're not using the source tarballs from GitHub though?

We like to be as close to what you are shipping to the user, e.g. pip, as possible. Secondly, pypi has a mirror system, which we love to use.

**Comment by borntyping** [comment]
The tests should now be included in the PyPI releases (version 2.6.2 and above). :smile:

**Comment by borntyping** [comment]
Should be fixed correctly now. I think putting tests in `$project/tests/` was also a user request at some point...
