### ISSUE TITLE
Wrong basic sample in Readme ?

### ISSUE THREAD

**Issue by sveetch** [borntyping/python-colorlog#30]
Hi, this a nice useful package.

To integrate it, i naively used the basic sample from Readme: https://github.com/borntyping/python-colorlog#usage

So i coded something like that:

```
root_logger = colorlog.getLogger("boussole")
root_logger.setLevel(level)
root_logger.setFormatter(colorlog.ColoredFormatter(
    '%(log_color)s%(levelname)s:%(name)s:%(message)s'))
root_logger.addHandler(logging.StreamHandler())
```

And this resulted in exception complaining about "Logger" that didn't have the `setFormatter` because this is only a method available from a handler.

Stopping to be so naive, i simply reformatted my code to set formatter from my handler and it works well:

```
    root_logger = logging.getLogger("boussole")
    root_logger.setLevel(level)
    handler = logging.StreamHandler()
    handler.setFormatter(
        colorlog.ColoredFormatter(
            '%(asctime)s - %(log_color)s%(message)s',
            datefmt="%H:%M:%S"
        )
    )

    root_logger.addHandler(handler)
```

Did i miss something or maybe your sample is not very accurate ?

**Comment by borntyping** [comment]
From a quick look at the documentation for `logging` it seems the example is wrong. I'll take a full look at it soon and make sure the example in the README is corrected if necessary.

**Comment by borntyping** [comment]
Thanks :heart:
