### ISSUE TITLE
Purpose of colorlog.getLogger()/StreamHandler()

### ISSUE THREAD

**Issue by gsauthof** [borntyping/python-colorlog#34]
Your example in the readme also uses colorlog.getLogger() and colorlog.StreamHandler() besides colorlog.ColoredFormatter(). I would expect that only a specialized Formatter is necessary for colorization. And indeed,  modifying the example such that only ColoredFormatter() with standard getLogger()/StreamHandler() is used, works as well. Why does colorlog also provide those methods?

**Comment by borntyping** [comment]
They are simply aliases for the same functions and objects from the logging module (see [logging.py](https://github.com/borntyping/python-colorlog/blob/master/colorlog/logging.py)). The examples should all work with both the `logging` and `colorlog` modules being interchangeable (except for `colorlog.ColoredFormatter`.
