### ISSUE TITLE
Can't get working on windows/powershell

### ISSUE THREAD

**Issue by springjools** [borntyping/python-colorlog#35]
I believe I have it set up correctly, but it just formats all text in while. is this supposed to work on windows 7 and powershell? What about cmd? I tested both.

http://pastebin.com/29qianDM

Python 2.7.11 and both colorama and colorlogs are installed.

**Comment by borntyping** [comment]
The format string you create the `ColoredFormatter` with (line 19) needs to include extra variables for color to be inserted. Try using `'%(log_color)s%(name)-12s: %(levelname)-8s %(message)s'`, which should color the whole message.
