### ISSUE TITLE
Color continuation in syslog

### ISSUE THREAD

**Issue by somada141** [borntyping/python-colorlog#43]
Consider the following snippet that simply creates a logger with a colourful formatter and logs a few messages:

```python
import sys
import logging
import logging.handlers
import colorlog


# create the logger with the appropriate name
logger = logging.getLogger(name="somelogger")
# set logger's log-level
logger.setLevel("DEBUG")

# assemble the logging format
fmt = 'someproject: %(process)d %(processName)s %(asctime)-15s %(levelname)-8s %(name)-10s %(message)s'

# create a colourful formatter
formatter_w_color = colorlog.ColoredFormatter(
    fmt="%(log_color)s" + fmt + %(reset)s,
    datefmt="%Y-%m-%dT%H:%M:%SZ",
    reset=True,
    log_colors={
        'DEBUG': 'blue',
        'INFO': 'green',
        'WARNING': 'yellow',
        'ERROR': 'red',
        'CRITICAL': 'red,bg_white',
    },
    secondary_log_colors={},
    style='%'
)

handler_stdout = logging.StreamHandler(sys.stdout)
handler_stdout.setFormatter(formatter_w_color)
logger.addHandler(handler_stdout)

handler_syslog = logging.handlers.SysLogHandler(address="/dev/log")
handler_syslog.setFormatter(formatter_w_color)
logger.addHandler(handler_syslog)


logger.debug("debug")
logger.info("debug")
logger.warning("debug")
logger.error("debug")
logger.critical("debug")
```

The stdout and syslog can also be seen in the following image:

![image](https://cloud.githubusercontent.com/assets/272419/22959188/5a858ab8-f388-11e6-978a-e03081362167.png)

As you can see it all looks good in `stdout` but in `syslog` there's a `#033[0m` that causes the colour to bleed into the next line until the next colour kicks in.

Am I doing sth inordinately stupid or is this to be expected from a syslog handler?

**Comment by borntyping** [comment]
This isn't expected, the string should end with `\003[0m` (the escape code that resets all colors). I'm not sure why this behavior happens - I generally recommend that you only use `colorlog` for terminal output, not for streaming to other log handlers.

**Comment by somada141** [comment]
as you said its probably cause it was used explicitly through the `SysLogHandler`. It does seem to work really well on `stdout` and even `upstart` logs so I'm quite happy :). Reckon you can close this but perhaps it'd be worth mentioning the limitation on the `README.md`.
