### ISSUE TITLE
Support auto-colors feature

### ISSUE THREAD

**Issue by vuolter** [borntyping/python-colorlog#44]
I found really interesting the ability to automatically change the text color according to the background. The colorclass package (https://pypi.python.org/pypi/colorclass) supports already that feature and I'd love to see it available here too, maybe replacing colorama. ;)

**Comment by borntyping** [comment]
This would require a lot of internal changes to `colorlog` (it currently handles color naming and escape codes itself), and would be very hard to do without breaking backwards compatibility. I'd be willing to consider a PR that implemented this though!
