### ISSUE TITLE
Colorlog 3.0.0: cannot use both foreground and background colors

### ISSUE THREAD

**Issue by florenthemmi** [borntyping/python-colorlog#47]
Hello,

Since the latest release (commit https://github.com/borntyping/python-colorlog/commit/604110371c60211fea0edfb86b866e4126f8878f), using both foreground and background colors in `ColorFormatter` seems not working anymore.

```python
formatter = ColoredFormatter(
	"%(log_color)s%(levelname)-8s%(reset)s %(blue)s%(message)s",
	datefmt=None,
	reset=True,
	log_colors={
		'DEBUG':    'cyan',
		'INFO':     'green',
		'WARNING':  'yellow',
		'ERROR':    'red',
		'CRITICAL': 'red,bg_white',
	},
	secondary_log_colors={},
	style='%'
)
```

In this example (same as the README), critical logging log without colors (same as reset).
Before (2.10.0)
<img width="366" alt="after" src="https://user-images.githubusercontent.com/4488419/28714815-7618a3e0-7395-11e7-9925-c3d4a80e98e0.png">
After (3.0.0)
<img width="370" alt="before" src="https://user-images.githubusercontent.com/4488419/28714808-71beb5fa-7395-11e7-82ee-777c4ae8393e.png">

Is it an expected behaviour?

Moreover, the `parse_colors` method has been removed but the README is not up to date.

Thanks for taking the time to answer me.
Regards,

**Comment by borntyping** [comment]
This should be fixed by https://github.com/borntyping/python-colorlog/commit/02410e5eedcd5994cfddc1adffb82b5429d991f0 and https://github.com/borntyping/python-colorlog/commit/39677296066d4c72e86a119af0def6f9b7a64843.
