### ISSUE TITLE
Mis-tagged version 3.0.1

### ISSUE THREAD

**Issue by cmcqueen** [borntyping/python-colorlog#49]
It seems the latest version is 3.0.1, but the tag says 3.1.0. Is this a typo?

**Comment by borntyping** [comment]
Just a typo. A fixed 3.1.0 has been pushed to PyPi.

**Comment by cmcqueen** [comment]
The tag `v3.1.0` in the git repository still points to the wrong commit that says version 3.0.1. And the GitHub release 3.1.0 likewise contains version 3.0.1.

**Comment by cmcqueen** [comment]
As stated above, the tag `v3.1.0` in the git repository is still incorrect. This issue should be fixed/re-opened.
