### ISSUE TITLE
List of color names, or property to import to use code autocomplete with?

### ISSUE THREAD

**Issue by a904guy** [borntyping/python-colorlog#50]
Is there a spot in the code that has all the available color name?

 I know it's based off of colorama, so can I just use those names?

P.S. Best log colorizer ever, Thank you for this project!

**Comment by borntyping** [comment]
You can find the color names in [`escape_codes.py`](https://github.com/borntyping/python-colorlog/blob/master/colorlog/escape_codes.py#L32-L41). All of them can be prefixed with `bold_`, `fg_`, `bg_`, or `thin_`.

(`colorama` is an optional dependency used for windows support, so I don't know if the names match.)

**Comment by saurabheights** [comment]
For white, you have following combination of values generated:- 
bold_white, thin_white, fg_white, fg_bold_white, fg_thin_white, bg_white, bg_bold_white
