### ISSUE TITLE
Switch to deactivate color output

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [borntyping/python-colorlog#51]
There should be a switch to deactivate the color output. Most of the time for debug purpose.

I use my code on Linux (bash) and Windwos10 (Thonny Pythton GUI). The latter is not able to handle the color codes and output all the escape characters. This is ugly.

I just want to deactivate the color-escape sequences but not the other settings (e.g. format).

**Comment by naggie** [comment]
Have you tried `colorlog.TTYColoredFormatter`? This should disable the codes if not running inside a TTY.

**Comment by buhtz** [comment]
Oh, I wasn't aware of that class. Great. Haven't tried it yet but I think this will fix the problem.

**Comment by buhtz** [comment]
It is not working with Thonny-IDE under Windows10. Looking at stackoverflow I can see there is no generalizable solution for that problem.

`os.environ` give some hints, too.

**Comment by borntyping** [comment]
You're probably better off just configuring a different formatter on Windows machines, with something like the following:

```
import platform
import logging
import colorlog

handler = logging.StreamHandler()
if platform.system() == 'Windows':
     handler.setFormatter(colorlog.ColoredFormatter('%(log_color)s%(levelname)s:%(name)s:%(message)s'))
else:
     handler.setFormatter(logging.Formatter('%(levelname)s:%(name)s:%(message)s'))

logger = colorlog.getLogger('example')
logger.addHandler(handler)
```

**Comment by buhtz** [comment]
It is a workaround but not a solution for this Issue. :)

**Comment by eblis** [comment]
This issue doesn't mention this but now you can disable colors by setting the `no_color` flag to `True`.

I was about to create a MR but noticed that the functionality is already there :)
