### ISSUE TITLE
[Feature request] Logbook support

### ISSUE THREAD

**Issue by Kristinita** [borntyping/python-colorlog#53]
### 1. Request

It would be nice, if you add [**`logbook`**](https://pypi.python.org/pypi/Logbook) support — a popular alternative default `logging` module.

### 2. Justification

I don't find Python modules, that support logbook. If I use modules for custom colored output as [**`pyfancy`**](https://github.com/ilovecode1/Pyfancy-2) or [**`colorama`**](https://pypi.python.org/pypi/colorama), I can highlight messages, but not `CRITICAL`, `ERROR`, `WARNING`, `NOTICE`, `INFO` and `DEBUG` words, example:

![NOTICE](https://i.imgur.com/No2350n.png)

It would be nice, if would be possible to highlight all logbook output.

Thanks.

**Comment by borntyping** [comment]
`colorlog` is deeply intertwined with the standard libraries `logging` module (it actually tries to provide the same API for common functions) - it'd probably be much simpler to borrow the useful parts from `colorlog` and start a new module. There's not very much that would be common between a handler for `logging` and for `logbook` aside from the escape codes.
