### ISSUE TITLE
colorlog[windows]

### ISSUE THREAD

**Issue by dheiman** [borntyping/python-colorlog#57]
when attempting to install colorlog[windows], I get the following warning:
`colorlog 3.1.2 does not provide the extra 'windows'`
And attempting to run anything that uses colorlog exits with the message:
`pkg_resources.UnknownExtra: colorlog 3.1.2 has no such extra feature 'windows'`

**Comment by borntyping** [comment]
Looks like this PR broke it: https://github.com/borntyping/python-colorlog/pull/25

Either the docs or `setup.py` need updating.

For now, you should be able to run `pip install colorlog` on windows and it should work correctly.

**Comment by AbdallahMostafa** [comment]
when i ran the setup.py in pycharm adding install as a script parameter it worked just fine and i didn't face that error

**Comment by borntyping** [comment]
The recommended way to install is just `colorlog`, additional dependencies should be worked out automatically.
