### ISSUE TITLE
colorlog doesn't strip colors when redirected to file

### ISSUE THREAD

**Issue by thorstenkampe** [borntyping/python-colorlog#64]
[Latest version of ccolorlog under Python 3.7.1]

colorlog doesn't strip color codes when redirected to a file or when running under Pytest. This happens only on Linux.

**Comment by thorstenkampe** [comment]
Minimal example to demonstrate the issue - save this as `logtest.py`:
```python
import colorlog
logger  = colorlog.getLogger()
handler = colorlog.StreamHandler()
handler.setFormatter(
    colorlog.TTYColoredFormatter('%(log_color)s%(message)s%(reset)s'))
logger.addHandler(handler)
logger.error('test')
```
```
./logtest.py
test  # printed red (GOOD)

./logtest.py > test.txt
test  # printed white - although we log to a TTY (BAD)

./logtest.py 2> test.txt
cat -v test.txt
^[[31mtest^[[0m  # color escapes not stripped (BAD)
```

**Comment by thorstenkampe** [comment]
On further investigation: when installing `colorama` on Linux - where it is not needed - issue #3 from above (redirecting stderr) goes away. Issue #2 (redirecting stdout) persists.

**Comment by borntyping** [comment]
This line should probably be changed so that the default stream a TTY formatter checks is stdout, matching the default stream used by the StreamHander: https://github.com/borntyping/python-colorlog/blob/master/colorlog/colorlog.py#L200
