### ISSUE TITLE
When redirecting stdout, prompt is colored with log level color

### ISSUE THREAD

**Issue by thorstenkampe** [borntyping/python-colorlog#65]
Given this minimal example (`logtest.py` - see below), the prompt is colored in red on Windows (cmd.exe):
![grafik](https://user-images.githubusercontent.com/475462/48411077-c4c57c00-e740-11e8-977c-94d7e839fad1.png)
```python
import colorlog
logger  = colorlog.getLogger()
handler = colorlog.StreamHandler()
handler.setFormatter(colorlog.ColoredFormatter(
    '%(log_color)s%(message)s%(reset)s'))
logger.addHandler(handler)
logger.error('test')
```

**Comment by borntyping** [comment]
See https://github.com/borntyping/python-colorlog/issues/64.
