### ISSUE TITLE
Installing license file

### ISSUE THREAD

**Issue by jubalh** [borntyping/python-colorlog#66]
It seems tarball from https://files.pythonhosted.org/packages/source/c/colorlog/colorlog-4.0.0.tar.gz does not install the LICENSE file by default.
Could you change it so the license is installed during setup?

**Comment by merwok** [comment]
The licence file is present in the sdist, but why would it need to be installed?

**Comment by jubalh** [comment]
Usually when I package something the license is also installed. For python-colorlog I had to do some extra stuff to install the license. I figured it should be installed by default so users know what license the program has.

**Comment by merwok** [comment]
That’s not standard Python practice.  Where is it installed?  Custom file in dist-info directory?

Licence files are included in sdists but not installed.
The package metadata however should contain a license classifier, and that is installed and queryable.

**Comment by jubalh** [comment]
> That’s not standard Python practice.

Hm interesting. I thought it was, but I was not very informed. Thanks.
