### ISSUE TITLE
Updating conda weblink in Readme

### ISSUE THREAD

**Issue by ManavalanG** [borntyping/python-colorlog#68]
Hi, [Weblink to Conda package](https://anaconda.org/auto/colorlog) in Readme is pointing to 5-year old package instead of the [recent (official?) site](https://anaconda.org/conda-forge/colorlog). The former is quite old now and supports only python2.7 in contrast to the latter.

**Comment by borntyping** [comment]
I don't have any involvement with any distributions of colorlog beyond this repository and [PyPi](https://pypi.org/project/colorlog/). It'd be very useful if you could make a PR updating the README to use a better link to the Conda distribution 😃

**Comment by ManavalanG** [comment]
Oh, I meant bad-link in [README](https://github.com/borntyping/python-colorlog/blob/master/README.md) of this repo (and apparently in PyPi site that you linked).
