### ISSUE TITLE
Simpler color syntax

### ISSUE THREAD

**Issue by cup** [borntyping/python-colorlog#69]
It seems this is the simplest for color output:

~~~py
import colorlog, logging
q = logging.StreamHandler()
q.setFormatter(colorlog.ColoredFormatter(
   "%(log_color)s%(levelname)s%(reset)s %(message)s",
   log_colors = {'INFO': 'green', 'WARNING': 'yellow', 'ERROR': 'red'}
))
z = logging.getLogger()
z.addHandler(q)
z.warning('abcde')
~~~

https://github.com/borntyping/python-colorlog/blob/master/doc/example.py

other projects have simpler syntax:

~~~py
from logzero import logger
logger.warning('abcde')
~~~

**Comment by borntyping** [comment]
Using `logging` or `colorlog`, you can do the following:

```
import colorlog
colorlog.basicConfig()
colorlog.warning("abcde")
```

```
import logging
logging.basicConfig()
logging.warning("abcde")
```

(See [`colorlog/logging.py`](https://github.com/borntyping/python-colorlog/blob/master/colorlog/logging.py#L13))

**Comment by cup** [comment]
@borntyping that is perfect! thanks
