### ISSUE TITLE
please support NO_COLOR

### ISSUE THREAD

**Issue by sandrotosi** [borntyping/python-colorlog#70]
https://no-color.org/

it would be great if we can set this variable to control if colors are printed or not

**Comment by GhostofGoes** [comment]
If you want the feature, you should open a PR, as I doubt borntyping will have the time to tackle this anytime soon. Seems like it'd be simple to implement, just read from `os.environ` on init, set a flag, then check the flag when configuring a logger.

**Comment by borntyping** [comment]
Support for `NO_COLOR` has been added in [6.0.0a2](https://pypi.org/project/colorlog/6.0.0a2/).

(This is a prerelease and may change before version `6.0.0`.)
