### ISSUE TITLE
Feature request: CSS colors

### ISSUE THREAD

**Issue by omry** [borntyping/python-colorlog#74]
It seems that currently only a very small number of colors is available (black, red, green, yellow, blue, purple, cyan and white).

Any thoughts on supporting hex representation for colors - maybe CSS color syntax?
https://www.w3schools.com/cssref/css_colors.asp

**Comment by etienne-napoleone** [comment]
This is related to the colors and color codes that are supported by terminals. You can change the color associated to each of those color cods in your terminal config.

See https://en.wikipedia.org/wiki/ANSI_escape_code

**Comment by omry** [comment]
Interesting, I didn't expect that.
I know that there are terminal emulations that supports 256 colors:

https://askubuntu.com/questions/821157/print-a-256-color-test-pattern-in-the-terminal

**Comment by borntyping** [comment]
A future version of colorlog might support 256 colour codes, at which point it might be possible to support this or something similar. Closing for now.
