### ISSUE TITLE
TTYColoredFormatter throwing a KeyError in newer versions of colorlog

### ISSUE THREAD

**Issue by mabouels** [borntyping/python-colorlog#75]
Upgrading colorlog from 2.10.0 to 4.0.2 results in the following error:

**/lib/python3.6/site-packages/colorlog/colorlog.py", line 200, in __init__
    self.stream = kwargs.pop('stream')
KeyError: 'stream'**

which originates from call to the constructor of TTYColoredFormatter

 `colorlog.TTYColoredFormatter(fmt='%(green)s[%(asctime)s]%(reset)s %(log_color)s%(message)s',
datefmt="%H:%M:%S",
                                             log_colors={'DEBUG': 'cyan',
                                                         'INFO': 'bold',
                                                         'WARNING': 'yellow',
                                                         'ERROR': 'bold_red',
                                                         'CRITICAL': 'red,bg_white'})`

**Comment by borntyping** [comment]
This is expected behavior, `TTYColoredFormatter` requires a `stream` argument as it otherwise has no way of knowing which stream is being used for logs.

See this commit: https://github.com/borntyping/python-colorlog/commit/40280b4bb36d8ad1a8bf1cfaa159a4a9066b1126
