### ISSUE TITLE
Illegal characters appear in the log file.

### ISSUE THREAD

**Issue by ykitadj** [borntyping/python-colorlog#81]
I used colorlog (4.1.0) to color debug output characters. Debug output characters on the display are functioning normally, but incorrect characters are printed in the log file.
For example,
[37m[2020-01-30 22:54:03,237] [MAI] [36mCheck : type(df_merged)
Such characters are output to the log file. it's like this : "[37m"
If I don't use colorlog, these incorrect characters are not output.

**Comment by borntyping** [comment]
This is expected. Use `TTYColoredFormatter` if you want to enable/disable the output of ANSI colour codes depending on where output is being directed.

Alternatively, configure `logging` with a standard formatter instead of a colorlog formatter when writing to a log file.
