### ISSUE TITLE
is it possilbe to provide log_colors via logging.config.dictConfig?

### ISSUE THREAD

**Issue by thugcee** [borntyping/python-colorlog#82]
Hi, 

I love elasticity of **colorlog** and I'd like to integrate it with our project, but we use an YAML file converted to `dict` to configure logging. I've tried something like this, but it doesn't work:
```
formatters:
  colorful:
    class: colorlog.ColoredFormatter
    format: "%(log_color)s %(message)s"
    log_colors:
        DEBUG: 'black'
        INFO: 'blue'
```

Is it possible to construct this file that log_colors is passed to `ColoredFormatter` constructor?

**Comment by borntyping** [comment]
I would expect something like the following to work with `logging.config.dictConfig`, using `()` instead of `class` as the key for the class to use. Hope this helps :)
```
formatters:
  colorful:
    (): colorlog.ColoredFormatter
    format: "%(log_color)s %(message)s"
    log_colors:
        DEBUG: 'black'
        INFO: 'blue'
```

https://docs.python.org/2/library/logging.config.html
https://github.com/borntyping/python-colorlog#with-dictconfig

**Comment by thugcee** [comment]
It has to be `class` and this part works good (`ColoredFormatter` is instantiated) . The problem is with passing `log_colors` dict. 
OK, I'll live with default colors :) and as there is no knows solution to this I'm closing the issue.

**Comment by dulm-today** [comment]
> I would expect something like the following to work with `logging.config.dictConfig`, using `()` instead of `class` as the key for the class to use. Hope this helps :)
> 
> ```
> formatters:
>   colorful:
>     (): colorlog.ColoredFormatter
>     format: "%(log_color)s %(message)s"
>     log_colors:
>         DEBUG: 'black'
>         INFO: 'blue'
> ```
> 
> https://docs.python.org/2/library/logging.config.html
> https://github.com/borntyping/python-colorlog#with-dictconfig

It should be:
```
formatters:
  colorful:
    (): colorlog.ColoredFormatter
    fmt: "%(log_color)s %(message)s"
    log_colors:
        DEBUG: 'black'
        INFO: 'blue'
```
