### ISSUE TITLE
Mypy support for colorlog

### ISSUE THREAD

**Issue by thdhondt** [borntyping/python-colorlog#83]
Hello,

First of all, thanks a lot for this great package!
I have been using it for over a year now and it has made my logs a lot clearer.

I was wondering if you had any plans to add support for type annotations in this library?

I have started making a stub file on my side, but a direct integration inside the library would of course be easier for maintenance.

Thanks in advance for your help.

Thomas

**Comment by borntyping** [comment]
I only do maintainance work on this library at the moment (most of my work on logging goes into [jsonlog](https://github.com/borntyping/jsonlog) now), but would accept merge requests adding stub files :)

At the moment colorlog still targets ancient Python 2 versions, so adding types into the code itself might not be practical.

**Comment by borntyping** [comment]
Type hints have been added in [6.0.0a2](https://pypi.org/project/colorlog/6.0.0a2/).

(This is a prerelease and may change before version `6.0.0`.)
