### ISSUE TITLE
White != white

### ISSUE THREAD

**Issue by chwba** [borntyping/python-colorlog#87]
Hi, coloramas 'white' is actually grey. To get real white, can you implement `colorama.Fore.LIGHTWHITE_EX`, to get actual white?

**Comment by borntyping** [comment]
Support for light colours has been added in [6.0.0a2](https://pypi.org/project/colorlog/6.0.0a2/).

In your case, you can use `light_white` instead of `white`.

(This is a prerelease and may change before version `6.0.0`.)
